{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .name }}
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - {{ .accessModes }}
  hostPath:
    path: {{ .path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .persistentVolumeClaim.claimName }}
spec:
  storageClassName: standard
  accessModes:
    - {{ .persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .persistentVolumeClaim.capacity }}
{{- end }}